"""
report_generator.py
===================
Generates a styled PDF analysis report from a pandas DataFrame and a list
of Plotly figures.  Called by app.py when the user clicks "Generate PDF Report".

Entry point:
    pdf_bytes = generate_report(df, figures_with_titles, dataset_name="My Data")
"""

import io
import warnings
import numpy as np
import pandas as pd
import plotly.io as pio
from datetime import datetime

warnings.filterwarnings("ignore")

# ── ReportLab imports ────────────────────────────────────────────────────────
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image, PageBreak, HRFlowable, KeepTogether,
)

# ── Palette (matches the dashboard) ─────────────────────────────────────────
C_NAVY   = HexColor("#0b1a30")
C_BLUE   = HexColor("#2196f3")
C_TEAL   = HexColor("#2bc9b6")
C_PINK   = HexColor("#ff4f81")
C_PURPLE = HexColor("#7b6ef6")
C_AMBER  = HexColor("#ffb703")
C_LIGHT  = HexColor("#f1f4f9")
C_BORDER = HexColor("#e5e7eb")
C_TEXT   = HexColor("#1c2b3a")
C_MUTED  = HexColor("#8a94a6")

PAGE_W, PAGE_H = A4
MARGIN = 2 * cm
USABLE_W = PAGE_W - 2 * MARGIN


# ── Figure → PNG bytes ───────────────────────────────────────────────────────
def _fig_to_png(fig, width=900, height=430):
    """Convert a Plotly figure to PNG bytes using kaleido 0.2.x."""
    try:
        return pio.to_image(fig, format="png", width=width, height=height, scale=2)
    except Exception as e:
        return None


# ── Custom canvas for header / footer on every page ─────────────────────────
def _make_page_template(canvas, doc):
    canvas.saveState()

    # Top header bar
    canvas.setFillColor(C_NAVY)
    canvas.rect(0, PAGE_H - 1.3 * cm, PAGE_W, 1.3 * cm, fill=1, stroke=0)
    canvas.setFillColor(white)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(MARGIN, PAGE_H - 0.85 * cm, "PayAnalytics — Digital Payments Analysis Report")
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(PAGE_W - MARGIN, PAGE_H - 0.85 * cm,
                           datetime.now().strftime("%d %b %Y"))

    # Bottom footer bar
    canvas.setFillColor(C_LIGHT)
    canvas.rect(0, 0, PAGE_W, 0.9 * cm, fill=1, stroke=0)
    canvas.setFillColor(C_MUTED)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(MARGIN, 0.3 * cm, "Generated by Digital Payments Trend Analyzer")
    canvas.drawRightString(PAGE_W - MARGIN, 0.3 * cm, f"Page {doc.page}")

    canvas.restoreState()


# ── Style helpers ────────────────────────────────────────────────────────────
def _styles():
    base = getSampleStyleSheet()
    return {
        "cover_title": ParagraphStyle(
            "CoverTitle", parent=base["Title"],
            fontSize=28, textColor=white,
            fontName="Helvetica-Bold", alignment=TA_CENTER,
            spaceAfter=8,
        ),
        "cover_sub": ParagraphStyle(
            "CoverSub", parent=base["Normal"],
            fontSize=13, textColor=HexColor("#b9c2d0"),
            alignment=TA_CENTER, spaceAfter=4,
        ),
        "section_heading": ParagraphStyle(
            "SectionHeading", parent=base["Normal"],
            fontSize=14, textColor=C_NAVY,
            fontName="Helvetica-Bold",
            spaceBefore=18, spaceAfter=8,
            borderPad=(0, 0, 4, 0),
        ),
        "chart_title": ParagraphStyle(
            "ChartTitle", parent=base["Normal"],
            fontSize=11, textColor=C_NAVY,
            fontName="Helvetica-Bold",
            spaceBefore=12, spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "Body", parent=base["Normal"],
            fontSize=10, textColor=C_TEXT,
            spaceAfter=5, leading=15,
        ),
        "muted": ParagraphStyle(
            "Muted", parent=base["Normal"],
            fontSize=9, textColor=C_MUTED,
            spaceAfter=4,
        ),
        "insight_item": ParagraphStyle(
            "InsightItem", parent=base["Normal"],
            fontSize=10, textColor=C_TEXT,
            leftIndent=12, spaceAfter=4, leading=15,
        ),
    }


def _section_divider(styles, title):
    """Return a styled section heading with a teal underline."""
    return [
        Paragraph(title, styles["section_heading"]),
        HRFlowable(width=USABLE_W, thickness=2, color=C_TEAL, spaceAfter=6),
    ]


def _kpi_table(rows):
    """Render a row of KPI mini-cards as a ReportLab table."""
    # rows = [(label, value), ...]
    labels = [r[0] for r in rows]
    values = [r[1] for r in rows]

    col_w = USABLE_W / len(rows)
    tbl = Table(
        [values, labels],
        colWidths=[col_w] * len(rows),
    )
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), C_NAVY),
        ("TEXTCOLOR",     (0, 0), (-1, 0), white),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 16),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, 0), 14),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("BACKGROUND",    (0, 1), (-1, 1), C_LIGHT),
        ("TEXTCOLOR",     (0, 1), (-1, 1), C_MUTED),
        ("FONTNAME",      (0, 1), (-1, 1), "Helvetica"),
        ("FONTSIZE",      (0, 1), (-1, 1), 8),
        ("TOPPADDING",    (0, 1), (-1, 1), 4),
        ("BOTTOMPADDING", (0, 1), (-1, 1), 8),
        ("GRID",          (0, 0), (-1, -1), 0.5, C_BORDER),
        ("ROUNDEDCORNERS", [4]),
    ]))
    return tbl


def _stats_table(desc_df):
    """Render a descriptive-statistics DataFrame as a styled table."""
    if desc_df is None or desc_df.empty:
        return None

    # Truncate wide tables to first 6 numeric columns
    cols = desc_df.columns.tolist()
    if len(cols) > 7:
        cols = cols[:7]
        desc_df = desc_df[cols]

    col_w_first = 2.2 * cm
    col_w_rest  = (USABLE_W - col_w_first) / max(len(cols) - 1, 1)

    header = [[Paragraph(f"<b>{c}</b>", ParagraphStyle("th", fontSize=8,
                textColor=white, fontName="Helvetica-Bold", alignment=TA_CENTER))
               for c in cols]]
    body = []
    for _, row in desc_df.iterrows():
        body.append([str(v) for v in row.values])

    data = header + body
    col_widths = [col_w_first] + [col_w_rest] * (len(cols) - 1)
    tbl = Table(data, colWidths=col_widths, repeatRows=1)
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), C_BLUE),
        ("TEXTCOLOR",     (0, 0), (-1, 0), white),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 0), (-1, -1), 8),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#f0f7ff"), white]),
        ("GRID",          (0, 0), (-1, -1), 0.4, C_BORDER),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return tbl


def _col_info_table(col_info):
    """Render column details as a styled table."""
    if not col_info:
        return None

    keys = list(col_info[0].keys())
    col_w = USABLE_W / len(keys)

    header = [[Paragraph(f"<b>{k}</b>",
                ParagraphStyle("th", fontSize=7.5, textColor=white,
                               fontName="Helvetica-Bold", alignment=TA_CENTER))
               for k in keys]]
    body = []
    for row in col_info:
        body.append([
            Paragraph(str(v)[:28],
                ParagraphStyle("td", fontSize=7.5, textColor=C_TEXT))
            for v in row.values()
        ])

    data = header + body
    tbl = Table(data, colWidths=[col_w] * len(keys), repeatRows=1)
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), C_PURPLE),
        ("TEXTCOLOR",     (0, 0), (-1, 0), white),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 0), (-1, -1), 7.5),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#f5f0fe"), white]),
        ("GRID",          (0, 0), (-1, -1), 0.4, C_BORDER),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return tbl


# ── Auto-generate insights from the DataFrame ────────────────────────────────
def _build_insights(df):
    """Return a list of plain-English insight strings about the data."""
    insights = []
    date_col, num_cols, cat_cols = _detect_columns(df)

    # Date range insight
    if date_col:
        mn = df[date_col].min()
        mx = df[date_col].max()
        span = (mx - mn).days
        insights.append(
            f"The dataset spans <b>{span} days</b> from "
            f"<b>{mn.strftime('%d %b %Y')}</b> to <b>{mx.strftime('%d %b %Y')}</b>."
        )

    # Numeric column insights
    for col in num_cols[:3]:
        mn_v = df[col].min()
        mx_v = df[col].max()
        avg  = df[col].mean()
        insights.append(
            f"<b>{col}</b>: min = {mn_v:,.2f}, max = {mx_v:,.2f}, "
            f"mean = {avg:,.2f}."
        )

    # Categorical insights
    for col in cat_cols[:3]:
        top_val   = df[col].value_counts().idxmax()
        top_count = df[col].value_counts().max()
        pct       = top_count / len(df) * 100
        insights.append(
            f"The most frequent <b>{col}</b> is <b>{top_val}</b>, "
            f"appearing in {top_count:,} records ({pct:.1f}% of total)."
        )

    # Missing data insight
    total_missing = int(df.isna().sum().sum())
    if total_missing > 0:
        insights.append(
            f"The dataset contains <b>{total_missing:,} missing values</b> "
            f"across all columns."
        )
    else:
        insights.append("The dataset is <b>complete</b> with no missing values.")

    return insights


def _detect_columns(df):
    """Mirrors the detect_columns logic from app.py (kept local to avoid circular imports).
    Parses the date column IN PLACE and returns (date_col, num_cols, cat_cols)."""
    date_col = None
    for col in df.columns:
        try:
            parsed = pd.to_datetime(df[col], dayfirst=True, errors="coerce")
            if parsed.notna().sum() / max(len(df), 1) > 0.7:
                df[col] = parsed          # mutate in-place so callers see datetimes
                date_col = col
                break
        except Exception:
            pass

    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    cat_cols = [
        c for c in df.columns
        if c != date_col
        and df[c].dtype == object
        and 2 <= df[c].nunique() <= 50
    ]
    return date_col, num_cols, cat_cols


# ── MAIN ENTRY POINT ─────────────────────────────────────────────────────────
def generate_report(df, figures_with_titles, dataset_name="Uploaded Dataset"):
    """
    Parameters
    ----------
    df : pandas.DataFrame
        The uploaded/analysed DataFrame.
    figures_with_titles : list of (str, plotly.Figure)
        Each tuple is (chart_title, figure_object).
    dataset_name : str
        Shown on the cover page and in headers.

    Returns
    -------
    bytes
        Raw PDF bytes, ready to be served via dcc.Download.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=MARGIN,
        leftMargin=MARGIN,
        topMargin=1.8 * cm,
        bottomMargin=1.5 * cm,
        title=f"Analysis Report — {dataset_name}",
        author="PayAnalytics",
    )

    S = _styles()
    story = []

    # Parse dates & detect columns ONCE on the live df so all sub-functions
    # see proper datetime types (not strings from JSON round-trip).
    date_col, num_cols, cat_cols = _detect_columns(df)

    # ── COVER PAGE ───────────────────────────────────────────────────────────
    story.append(Spacer(1, 3 * cm))

    # Dark navy cover block
    cover_data = [[
        Paragraph("📊 Digital Payments Trend Analyzer", S["cover_title"]),
        Paragraph("Data Analysis Report", S["cover_sub"]),
        Paragraph(dataset_name, S["cover_sub"]),
        Paragraph(datetime.now().strftime("%d %B %Y  ·  %H:%M"), S["cover_sub"]),
    ]]
    cover_tbl = Table(cover_data, colWidths=[USABLE_W])
    cover_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), C_NAVY),
        ("TOPPADDING",    (0, 0), (-1, -1), 32),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 32),
        ("LEFTPADDING",   (0, 0), (-1, -1), 24),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 24),
        ("ROUNDEDCORNERS", [8]),
    ]))
    story.append(cover_tbl)
    story.append(Spacer(1, 1.5 * cm))

    # KPI mini-cards on cover
    kpi_data = [
        (f"{len(df):,}", "Total Records"),
        (str(len(df.columns)), "Columns"),
        (str(len(num_cols)), "Numeric Cols"),
        (str(len(cat_cols)), "Categorical Cols"),
    ]
    story.append(_kpi_table(kpi_data))
    story.append(PageBreak())

    # ── SECTION 1 — DATASET OVERVIEW ────────────────────────────────────────
    story += _section_divider(S, "1.  Dataset Overview")

    total_missing = int(df.isna().sum().sum())
    duplicates    = int(df.duplicated().sum())

    # Date range
    if date_col and df[date_col].dtype != object:
        mn = df[date_col].min()
        mx = df[date_col].max()
        story.append(Paragraph(
            f"Date range: <b>{mn.strftime('%d %b %Y')}</b> → "
            f"<b>{mx.strftime('%d %b %Y')}</b>  "
            f"({(mx - mn).days} days)",
            S["body"],
        ))

    story.append(Paragraph(
        f"Missing values: <b>{total_missing:,}</b>  ·  "
        f"Duplicate rows: <b>{duplicates:,}</b>  ·  "
        f"Memory usage: <b>{df.memory_usage(deep=True).sum() / 1024:.1f} KB</b>",
        S["body"],
    ))
    story.append(Spacer(1, 0.3 * cm))

    # Column details table
    col_info = []
    for c in df.columns:
        col_info.append({
            "Column":    c[:22],
            "Type":      str(df[c].dtype),
            "Non-Null":  int(df[c].notna().sum()),
            "Missing":   int(df[c].isna().sum()),
            "Unique":    int(df[c].nunique()),
            "Sample":    str(df[c].dropna().iloc[0])[:20] if df[c].notna().any() else "N/A",
        })
    col_tbl = _col_info_table(col_info)
    if col_tbl:
        story.append(col_tbl)
    story.append(Spacer(1, 0.4 * cm))

    # ── SECTION 2 — STATISTICAL SUMMARY ─────────────────────────────────────
    story += _section_divider(S, "2.  Statistical Summary")

    if num_cols:
        desc = df[num_cols].describe().round(2).reset_index()
        desc.rename(columns={"index": "Statistic"}, inplace=True)
        stat_tbl = _stats_table(desc)
        if stat_tbl:
            story.append(stat_tbl)
    else:
        story.append(Paragraph("No numeric columns found in this dataset.", S["muted"]))

    story.append(PageBreak())

    # ── SECTION 3 — KEY INSIGHTS ─────────────────────────────────────────────
    story += _section_divider(S, "3.  Key Insights")

    insights = _build_insights(df)   # df already has parsed dates from _detect_columns above
    for i, text in enumerate(insights, 1):
        story.append(Paragraph(f"  {i}.  {text}", S["insight_item"]))

    story.append(Spacer(1, 0.6 * cm))

    # ── SECTION 4 — ANALYSIS CHARTS ──────────────────────────────────────────
    story += _section_divider(S, "4.  Analysis Charts")

    if not figures_with_titles:
        story.append(Paragraph("No charts were generated for this dataset.", S["muted"]))
    else:
        story.append(Paragraph(
            f"{len(figures_with_titles)} charts generated automatically based on the "
            f"detected column types in your dataset.",
            S["body"],
        ))
        story.append(Spacer(1, 0.4 * cm))

        for idx, (title, fig) in enumerate(figures_with_titles, 1):

            png = _fig_to_png(fig, width=900, height=420)

            chart_block = []
            # Numbered chart title with teal accent
            chart_block.append(Paragraph(f"Chart {idx} — {title}", S["chart_title"]))
            chart_block.append(HRFlowable(
                width=USABLE_W, thickness=1,
                color=C_TEAL, spaceAfter=6,
            ))

            if png:
                img_h = USABLE_W * 420 / 900
                chart_block.append(
                    Image(io.BytesIO(png), width=USABLE_W, height=img_h)
                )
            else:
                chart_block.append(Paragraph(
                    f"[Chart could not be rendered]", S["muted"]
                ))

            chart_block.append(Spacer(1, 0.6 * cm))

            # Keep title + chart together; add page break between charts
            story.append(KeepTogether(chart_block))
            if idx < len(figures_with_titles):
                story.append(PageBreak())

    # ── SECTION 5 — SUMMARY ──────────────────────────────────────────────────
    story.append(PageBreak())
    story += _section_divider(S, "5.  Report Summary")

    summary_data = [
        ["Dataset",           dataset_name],
        ["Total Records",     f"{len(df):,}"],
        ["Total Columns",     str(len(df.columns))],
        ["Numeric Columns",   str(len(num_cols))],
        ["Categorical Cols",  str(len(cat_cols))],
        ["Missing Values",    str(total_missing)],
        ["Charts Generated",  str(len(figures_with_titles))],
        ["Report Generated",  datetime.now().strftime("%d %B %Y, %H:%M:%S")],
    ]
    sum_tbl = Table(summary_data, colWidths=[6 * cm, USABLE_W - 6 * cm])
    sum_tbl.setStyle(TableStyle([
        ("FONTNAME",      (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",      (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 0), (-1, -1), 10),
        ("TEXTCOLOR",     (0, 0), (0, -1), C_NAVY),
        ("TEXTCOLOR",     (1, 0), (1, -1), C_TEXT),
        ("ROWBACKGROUNDS",(0, 0), (-1, -1), [C_LIGHT, white]),
        ("GRID",          (0, 0), (-1, -1), 0.4, C_BORDER),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
    ]))
    story.append(sum_tbl)

    story.append(Spacer(1, 1 * cm))
    story.append(Paragraph(
        "This report was automatically generated by the Digital Payments Trend Analyzer. "
        "All charts and statistics are derived from the uploaded dataset.",
        S["muted"],
    ))

    # ── BUILD PDF ────────────────────────────────────────────────────────────
    doc.build(story, onFirstPage=_make_page_template, onLaterPages=_make_page_template)
    buffer.seek(0)
    return buffer.read()
